version: 2
jobs:
  build:
    docker:
      - image: ubuntu:xenial
    steps:
      - run:
          name: install git and ssh
          command: apt-get update && apt-get install -y git ssh
      - run:
          name: Connect to remote VPS
          command: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@34.241.9.84 'echo $HOSTNAME'
      - run:
          name: Install mysql client and sshuttle
          command: apt-get install -y mysql-client sshuttle
      - run:
          name: Establish ssh tunnel for traffic to AWS VPC
          command: sudo sshuttle --daemon -r ubuntu@34.241.9.84 -e 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' 172.31.0.0/16
      - run:
          name: Execute test mysql command
          command: mysql -u circleci -pcircleci -h test-circleci.cluster-canclhgmdpqd.eu-west-1.rds.amazonaws.com -e 'SELECT VERSION()'
      - run:
          name: Kill ssh tunnel
          command: sudo kill `echo sshuttle.pid`
