version: 2
jobs:
  build:
    docker:
      - image: ubuntu:xenial
    steps:
      - run: apt-get update && apt-get install -y ssh git
      - add_ssh_keys
      - checkout
      - run: ls ~/.ssh/*
      - run: cat ~/.ssh/*
